In [1]:
import numpy as np


In [6]:
matrix=np.array([[5,10,15],[20,25,30],[35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [7]:
# Indexingusing double bracket notation

matrix[1][1]


25

In [8]:
#  Indexing using single bracket notataion

matrix[1,1]

25

In [9]:
#  Slicing using single bracket notation

matrix[0:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [11]:
np.random.seed(123)
matrix2=np.random.randint(1,101,25).reshape(5,5)
matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [12]:
matrix2[1:-1,1:-1]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])