In [1]:
import numpy as np

In [6]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr3=np.array([9,10,11,12])

In [7]:
arr1+arr2

array([ 6,  8, 10, 12])

In [8]:
arr1*arr2

array([ 5, 12, 21, 32])

In [9]:
arr1**arr2+arr3

array([   10,    74,  2198, 65548])

In [11]:
np.random.seed(123)
matrix1=np.random.randint(1,12,9).reshape(3,3)
matrix2=np.random.randint(5,15,9).reshape(3,3)

In [12]:
matrix1+matrix2

array([[ 8,  9, 21],
       [ 7,  9, 25],
       [18, 16,  7]])

In [14]:
matrix1*matrix2

array([[ 15,  18,  98],
       [ 10,  20, 154],
       [ 80,  63,  10]])

In [15]:
matrix1.dot(matrix2)

array([[ 86,  96, 119],
       [118, 131, 139],
       [101, 113, 248]])