In [1]:
import numpy as np 


In [2]:
arr=np.array([2,80,1,97,5])

In [3]:
# for minimum value
np.min(arr)

1

In [4]:
#  for maximum value
np.max(arr)

97

In [5]:
# position of minimum value
np.argmin(arr)

2

In [6]:
#  position of maximum value
np.argmax(arr)

3

In [7]:
#  for square root of all value
np.sqrt(arr)

array([1.41421356, 8.94427191, 1.        , 9.8488578 , 2.23606798])

In [9]:
# exponential value
np.exp(arr)

array([7.38905610e+00, 5.54062238e+34, 2.71828183e+00, 1.33833472e+42,
       1.48413159e+02])

In [10]:
#  for sine value
np.sin(arr)

array([ 0.90929743, -0.99388865,  0.84147098,  0.37960774, -0.95892427])

In [12]:
# for cosine value
np.cos(arr)

array([-0.41614684, -0.11038724,  0.54030231, -0.92514754,  0.28366219])

In [16]:
#  for equal spacing
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
#  for boolean value
arr2=np.array([1,0,4,-4],dtype='bool')
arr2

array([ True, False,  True,  True])