In [33]:
import numpy as np

In [34]:
arr=np.array([5,10,15,20,25,30])

In [35]:
# View

sliced_arr=arr[2:5]

In [36]:
sliced_arr

array([15, 20, 25])

In [37]:
sliced_arr[:]=0

In [38]:
sliced_arr

array([0, 0, 0])

In [39]:
arr

array([ 5, 10,  0,  0,  0, 30])

In [ ]:
#  Copy

In [40]:
array=np.array([2,4,6,8,10])

In [41]:
array

array([ 2,  4,  6,  8, 10])

In [46]:
new=array[:3].copy()
new

array([2, 4, 6])

In [47]:
new[:]=0

In [48]:
new

array([0, 0, 0])

In [49]:
array

array([ 2,  4,  6,  8, 10])